### ISSUE TITLE
skynet中如果有多个webclient服务时，有时关闭进程会报错。

### ISSUE THREAD

**Issue by albus0x01** [dpull/lua-webclient#1]
具体是webclient_destory函数里的curl_multi_cleanup。
用skynet.abort关闭，有时候会报错。

**Comment by albus0x01** [comment]
找到原因了， webclient->encoding_curl 没初始化的原因。

**Comment by dpull** [comment]
你感觉要怎么改比较好？

**Comment by albus0x01** [comment]
webclient_create里 
webclient->encoding_curl = NULL;
毕竟每个服务会create一次。

**Comment by dpull** [comment]
多谢，是我疏忽了
