### ISSUE TITLE
resolve timeout

### ISSUE THREAD

**Issue by darjun** [dpull/lua-webclient#10]
我将test.lua中urls改成https://api.mch.weixin.qq.com/pay/unifiedorder，运行出现Resolving timed out
https://api.mch.weixin.qq.com/pay/unifiedorder 0 Resolving timed out after 5000 milliseconds  0 -1.0 0

但是同一台机器用curl能返回结果：
curl -f https://api.mch.weixin.qq.com/pay/unifiedorder                                
<xml><return_code><![CDATA[FAIL]]></return_code><return_msg><![CDATA[请使用post方法]]></return_msg></xml>%

**Comment by dpull** [comment]
域名解析问题，建议增加host

**Comment by darjun** [comment]
如何增加这个host呢？

**Comment by dpull** [comment]
你可以google
