### ISSUE TITLE
libcurl版本在7.17.1之后,POST数据会异常

### ISSUE THREAD

**Issue by CoolDesert** [dpull/lua-webclient#11]
CURLOPT_POSTFIELDS 在7.17.1版本以后不会拷贝post数据

另外新增了一个选项:CURLOPT_COPYPOSTFIELDS 

提此issue，希望后面使用这个库的同学不要掉坑了...

**Comment by dpull** [comment]
我研究下

**Comment by CoolDesert** [comment]
这么改的话最好限制下版本号，CURLOPT_COPYPOSTFIELDS 这个选项在7.17.1之前是不存在的

**Comment by dpull** [comment]
没必要了，十年前的版本了

  | curl-7.17.1.tar.gz | 2008-01-03 16:12 | 2.1M |
