### ISSUE TITLE
undefined symbol: curl_easy_escape，链接错误已解决

### ISSUE THREAD

**Issue by peigongdh** [dpull/lua-webclient#13]
遇到了这个issues中同样的问题，加入链接-lcurl后仍然报错

[#8](https://github.com/dpull/lua-webclient/issues/8)
`undefined symbol: curl_easy_escape`

已解决，在这里补充一下，链接的时候要把-lcurl加在后面，像这样：
`cc -g -O2 -Wall -Iskynet/3rd/lua  -fPIC --shared -Iserver/lualib-src/webclient server/lualib-src/webclient.c -o server/luaclib/webclient.so -lcurl`
如果是这样把链接库选项加在中间则会报错：
`cc -g -O2 -Wall -Iskynet/3rd/lua  -fPIC --shared -Iserver/lualib-src/webclient  -lcurl server/lualib-src/webclient.c -o server/luaclib/webclient.so`

附一个参考makefile：
```
include platform.mk

LUA_CLIB_PATH ?= server/luaclib

LUA_CLIB = webclient

CFLAGS = -g -O2 -Wall -I$(LUA_INC) $(MYCFLAGS)

# lua
LUA_STATICLIB := skynet/3rd/lua/liblua.a
LUA_LIB ?= $(LUA_STATICLIB)
LUA_INC ?= skynet/3rd/lua

all : \
    $(foreach v, $(LUA_CLIB), $(LUA_CLIB_PATH)/$(v).so)

$(LUA_CLIB_PATH)/webclient.so : server/lualib-src/webclient.c | $(LUA_CLIB_PATH)
	$(CC) $(CFLAGS) $(SHARED) -Iserver/lualib-src/webclient $^ -o $@ -lcurl
```

可关闭该issues或保留作为参考

**Comment by dpull** [comment]
谢谢  看样我要补一个makefile才好
