### ISSUE TITLE
设置timeout无效

### ISSUE THREAD

**Issue by luca-666** [dpull/lua-webclient#16]
设置cURL允许执行的最长毫秒数无效，超过设定时间后没有返回

**Comment by dpull** [comment]
这个是没有设置  现有的那个超时是connect的时间超时，请问你用总体超时这个要用于什么情况，可否说一下？

因为我接触的业务中，没有需求设置curl允许执行的超时，想听听你的。

**Comment by luca-666** [comment]
curl_easy_setopt(handle, CURLOPT_CONNECTTIMEOUT_MS, connect_timeout_ms);
我说的超时就是指的连接超时，我看代码里默认设置是5秒。当请求超过5秒后通过webclient:query()无法查询到返回，感觉这里有个超时的错误返回比较好。现在我是在lua调用的地方加了定时器做的处理。

**Comment by dpull** [comment]
CONNECTTIMEOUT 仅仅是connect是超时，如果connect上了，但是服务器没返回传输完成，还是要等的,你想要的会不会是 CURLOPT_TIMEOUT

**Comment by luca-666** [comment]
哦哦，不好意思，是我误解了CURLOPT_CONNECTTIMEOUT_MS的含义。我需要的应该是CURLOPT_TIMEOUT。不过我测试了下现在CURLOPT_CONNECTTIMEOUT_MS设置的默认值5000ms,但是连接超时9秒左右才返回了超时的错误信息：Recv failure: Connection reset by peer。

**Comment by dpull** [comment]
这个不是因为设置CURLOPT_CONNECTTIMEOUT_MS 超时失败的返回值吧
