### ISSUE TITLE
设置headers无效

### ISSUE THREAD

**Issue by xuyang-max** [dpull/lua-webclient#17]
看了源码
if (top > 2 && lua_istable(l, 3)) {
        http_post = webclient_tohttppost(l, 3);
        if (!http_post)
            return luaL_argerror(l, 3, "parameter post_form invalid");
    }
    else if (top > 2 && lua_isstring(l, 3)) {
        postdata = lua_tolstring(l,3, &postdatalen);
    }

    if (top > 3 && lua_isnumber(l, 4)) {
        connect_timeout_ms = (long)lua_tointeger(l, 4);
        if (connect_timeout_ms < 0)
            return luaL_argerror(l, 4, "parameter connect_timeout_ms invalid");
    }

源码中if (top > 2 && lua_istable(l, 3)) { 栈上第三个参数如果是table就设置headers，然后下面postdata也是栈上第三个参数，这里是否有误，我理解是url，headers，postdata，timeout。。。这样的排序，现在headers和data是不能同时设置的。

还有就是headers的table格式是什么样的，我这边设置是
local headers = {
    ["content_type"] = "application/json"
}
实际测试会出现Segmentation fault (core dumped)

**Comment by xuyang-max** [comment]
看了post的例程，使用webclient:set_httpheader已经可以用了，只是上面还是不是很理解，是否可以用webclient:request一次性把header和json数据（我这边要传json格式字符串）发出去

**Comment by dpull** [comment]
可以啊，不过参数已经好多了，这样真的好吗？
