### ISSUE TITLE
依赖的lua版本号不存在

### ISSUE THREAD

**Issue by cuixin** [dpull/lua-webclient#18]
在拉取依赖的lua版本号时，目标库的版本不存在，请更新依赖的lua版本号，谢谢。

**Comment by dpull** [comment]
你pr一下？

**Comment by cuixin** [comment]
很尴尬的是最新的github.com/lua/lua库没有lua5.3.5版本，您这个版本貌似不是5.3.4，我更新到master？

**Comment by cuixin** [comment]
这个依赖还是自己解决吧，我close了，各人用的lua版本不一样，我只能自己fork一份出来了。
