### ISSUE TITLE
请问大佬如何加上ssl功能

### ISSUE THREAD

**Issue by samoyedsun** [dpull/lua-webclient#19]

**Comment by dpull** [comment]
curl本来就支持啊

**Comment by Ron2014** [comment]
Windows 上 WinSSL 是本来就支持的，但是 POSIX 的 OpenSSL 还是需要自己接的。当然还有其他的SSL

**Comment by dpull** [comment]
> Windows 上 WinSSL 是本来就支持的，但是 POSIX 的 OpenSSL 还是需要自己接的。当然还有其他的SSL

建议怎么搞?
