### ISSUE TITLE
能否附带makefile文件

### ISSUE THREAD

**Issue by cls1991** [dpull/lua-webclient#3]

**Comment by dpull** [comment]
如果用skynet的话 建议直接修改一下它的makefile，增加一个so就好了。

**Comment by cls1991** [comment]
skynet中使用, 报以下错误: 
:00000018(1486429408.35)[2017-02-07 09:03:28]: lua loader error : error loading module 'webclient' from file './luaclib/webclient.so':
	./luaclib/webclient.so: undefined symbol: curl_easy_escape
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	./mainserver/webclient.lua:7: in local 'main'
	./skynet/lualib/loader.lua:48: in main chunk
:00000018(1486429408.35)[2017-02-07 09:03:28]: KILL self
:00000008(1486429408.35)[2017-02-07 09:03:28]: init service failed: ./skynet/lualib/skynet.lua:535: ./skynet/service/service_mgr.lua:25: ./skynet/lualib/skynet.lua:381: call failed
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:535: in function 'skynet.uniqueservice'
	./mainserver/main.lua:15: in local 'start'
	./skynet/lualib/skynet.lua:619: in function <./skynet/lualib/skynet.lua:616>
	[C]: in function 'xpcall'
	./skynet/lualib/skynet.lua:623: in function 'skynet.pcall'
	./skynet/lualib/skynet.lua:627: in function 'skynet.init_service'
	./skynet/lualib/skynet.lua:640: in upvalue 'f'
	./skynet/lualib/skynet.lua:104: in function <./skynet/lualib/skynet.lua:103>
