### ISSUE TITLE
skynet使用, 报错

### ISSUE THREAD

**Issue by cls1991** [dpull/lua-webclient#4]
skynet中使用, 报以下错误:
:00000018(1486429408.35)[2017-02-07 09:03:28]: lua loader error : error loading module 'webclient' from file './luaclib/webclient.so':
./luaclib/webclient.so: undefined symbol: curl_easy_escape
stack traceback:
[C]: in ?
[C]: in function 'require'
./mainserver/webclient.lua:7: in local 'main'
./skynet/lualib/loader.lua:48: in main chunk
:00000018(1486429408.35)[2017-02-07 09:03:28]: KILL self
:00000008(1486429408.35)[2017-02-07 09:03:28]: init service failed: ./skynet/lualib/skynet.lua:535: ./skynet/service/service_mgr.lua:25: ./skynet/lualib/skynet.lua:381: call failed
stack traceback:
[C]: in function 'assert'
./skynet/lualib/skynet.lua:535: in function 'skynet.uniqueservice'
./mainserver/main.lua:15: in local 'start'
./skynet/lualib/skynet.lua:619: in function <./skynet/lualib/skynet.lua:616>
[C]: in function 'xpcall'
./skynet/lualib/skynet.lua:623: in function 'skynet.pcall'
./skynet/lualib/skynet.lua:627: in function 'skynet.init_service'
./skynet/lualib/skynet.lua:640: in upvalue 'f'
./skynet/lualib/skynet.lua:104: in function <./skynet/lualib/skynet.lua:103>

**Comment by dpull** [comment]
你的libcurl.so的版本太老了，更新下，或者你改一下代码，改成使用 `curl_escape`

`curl_easy_escape` Added in 7.15.4 and replaces the old `curl_escape` function.

https://curl.haxx.se/libcurl/c/curl_easy_escape.html

**Comment by cls1991** [comment]
➜  CardGameHall git:(develop) ✗ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**Comment by cls1991** [comment]
➜ CardGameHall git:(develop) ✗ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**Comment by dpull** [comment]
这样吧，你把curl静态链接，看看有啥问题

**Comment by LokerLi** [comment]
我也遇到这个问题，楼上怎么解决的？

**Comment by abincai** [comment]
一样遇到这个问题，也在看怎么处理

**Comment by cls1991** [comment]
稍微绕了一下, python tornado处理https请求, skynet http链接之, @LokerLi @abincai

**Comment by LokerLi** [comment]
找到问题了，cc的时候加 -lcurl 就好了 @cls1991 @abincai

**Comment by dpull** [comment]
@lokerli 👍

**Comment by abincai** [comment]
@LokerLi 谢谢，昨天也找到问题了，刚才还打算来回复呢
