### ISSUE TITLE
request 失败的问题

### ISSUE THREAD

**Issue by korialuo** [dpull/lua-webclient#8]
我用nginx挂了一个test.php。里面就一句<?php echo "hello" ?>。 浏览器访问能正常显示“hello”字符串。但是skynet.call("webclient", "lua", "request", "http://localhost/test.php")的时候，会在webclient.lua的第37行(xpcall那一句)报错。

**Comment by korialuo** [comment]
另外，我linux-mint18.1安装了libcurl4-openssl-dev(curl版本7.47.0)，并且Makefile里加上了-lcurl，编译能通过，但是在使用的时候还是会报错，提示找不到curl_easy_escape这个symbol。在mac下就没问题。

**Comment by dpull** [comment]
问题1:是不是因为你没有log那个文件
问题2:是动态链接的curl不？如果是可能环境中存在多个curl

**Comment by korialuo** [comment]
1. local logger = require "log"  我屏蔽了。logger.Error() 我换成了print()。
2. 我是apt-get install libcurl4-openssl-dev这样安装的。也查找过，确实只有这一个curl库。

另外我换个发行版(ubuntu 17.04) 再试试。

**Comment by korialuo** [comment]
对于第2个问题，原因找到了，是因为ubuntu下的libcurl.so是放到/usr/lib/x86-64-linux-gnu下面去了，而ld根本不搜索这个目录。
第1个问题由于我对源码不够熟悉，暂时还没找到原因。

**Comment by dpull** [comment]
--- 请求某个url
-- @function request
-- @string url url
-- @tab[opt] get get的参数
-- @param[opt] post post参数，table or string类型 
-- @bool[opt] no_reply 使用skynet.call则要设置为nil或false，使用skynet.send则要设置为true
-- @treturn bool 请求是否成功
-- @treturn string 当成功时，返回内容，当失败时，返回出错原因 
-- @usage skynet.call(webclient, "lua", "request", "http://www.dpull.com")
-- @usage skynet.send(webclient, "lua", "request", "http://www.dpull.com", nil, nil, true)
local function request(url, get, post, no_reply)

是不是使用了skynet.send 但没有设置no_reply参数

**Comment by korialuo** [comment]
前两天太忙了，没及时回复。
我是用的skynet.call("webclient", "lua", "request", "http://localhost/test.php")。没用skynet.send。

**Comment by dpull** [comment]
把输出的堆栈贴一下

**Comment by korialuo** [comment]
我现在还没解决ubuntu17.04下使用的问题。编译通过，在skynet里require "webclient"的时候总是报错：undefind symbol: curl_easy_escape()。在mac下又没问题。

(已申请加你QQ好友，等待验证)

**Comment by dpull** [comment]
编译问题参考这个：https://github.com/dpull/lua-webclient/issues/4

QQ扯淡用的，技术类的问题在这讨论吧，有记录

**Comment by korialuo** [comment]
#4 这个issue我也看过  加了-lcurl 编译能通过。但是使用的时候报错undefined symbol。

刚才我把编译器改为了clang，这两个问题就都解决了。。再换回gcc仍然有问题。。我再查查什么原因。

**Comment by dpull** [comment]
这问题很简单：你的链接的libcurl.so和运行时的libcurl.so不是一个。

更新到最新版本，最新版本已经检查运行时curl的版本号了。

**Comment by korialuo** [comment]
好的  3Q。。

**Comment by ysjhbukn** [comment]
我使用你的示例...结合skynet  直接使用 webclient.lua  的request  但是怎么拿到返回的值呢..我郁闷了好久...看到请回复下..谢谢

**Comment by dpull** [comment]
@ysjhbukn 
-- @usage skynet.call(webclient, "lua", "request", "http://www.dpull.com")
